ESP/conf/urls.py
'''
                              ESP Health Project
                             Configuration Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django.conf.urls import url
from ESP.conf import views

urlpatterns = [
    url(r'^codes/ignore/(?P<native_code>.+)/$', views.ignore_code, name='ignore_code'),
    #change name worst case .. good point TODO 
    url(r'^codes/reportables/', views.heuristic_reportables, name='heuristic_reportables'),
    url(r'^codes/report', views.heuristic_mapping_report, name='heuristic_mapping_report'),
    #url(r'^json_code_grid', json_code_grid, name='json_code_grid'),
]

ESP/ui/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2010 Channing Laboratory
@license: LGPL
'''


from django.conf.urls import url
from ESP.ui import views

urlpatterns = [
    url(r'^labtest/lookup/$', views.labtest_lookup, name='labtest_lookup'),
    url(r'^labtest/detail/$', views.labtest_detail, name='labtest_detail'),
    url(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    url(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    url(r'^labtest/ignore_set/$', views.ignore_code_set, name='ignore_code_set'),
    url(r'^labtest/map/(?P<native_code>.+)/$', views.map_native_code, name='map_native_code'),
    url(r'^labtest/unmapped/$', views.unmapped_labs_report, name='unmapped_labs_report'),
    #
    #-------------------------------------------------------------------------------
    # Nodis
    #-------------------------------------------------------------------------------
    #
    url(r'^cases/$', views.case_list, {'status': 'all'}, name='nodis_cases_all'),
    url(r'^cases/list/awaiting_review/$', views.case_list, {'status': 'await'}, name='nodis_cases_awaiting_review'),
    url(r'^cases/list/under_review/$', views.case_list, {'status': 'under'}, name='nodis_cases_under_review'),
    url(r'^cases/list/queued/$', views.case_list, {'status': 'queued'}, name='nodis_cases_queued'),
    url(r'^cases/list/sent/$', views.case_list, {'status': 'sent'}, name='nodis_cases_sent'),
    url(r'^cases/list/requeued/$', views.case_list, {'status': 'requeued'}, name='nodis_cases_requeued'),
    #
    # Case Detail
    #
    url(r'^cases/view/(?P<case_id>\d+)/$', views.case_detail, name='nodis_case_detail'),
    url(r'^cases/viewpert/(?P<case_id>\d+)/$', views.pertussis_detail, name='nodis_pertussis_detail'),
    url(r'^cases/update/(?P<case_id>\d+)/$', views.case_status_update, name='nodis_case_update'),
    url(r'^cases/transmit/(?P<case_id>\d+)/$', views.case_queue_for_transmit, name='nodis_case_transmit'),
    url(r'^provider/(?P<provider_id>\w+)/$', views.provider_detail, name='provider_detail'),
    url(r'^patient/(?P<patient_pk>\d+)/records/$', views.all_records, name='all_records'),
    #
    # Validator
    #
    url(r'^validate/$', views.validator_summary, name='validator_summary'),
    url(r'^validate/missing/$', views.validate_missing, name='validate_missing'),
    url(r'^validate/missing/case/(?P<result_id>\d+)/$', views.missing_case_detail, name='missing_case_detail'),
    url(r'^validate/new/$', views.validate_new, name='validate_new'),
    url(r'^validate/similar/$', views.validate_similar, name='validate_similar'),
    url(r'^validate/exact/$', views.validate_exact, name='validate_exact'),

]

ESP/urls.py
'''
URLs for entire ESP Health django project

'''
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from ESP.settings import MEDIA_ROOT
from ESP.ui.views import status_page
from ESP.ui.views_survey import generate_survey_report, view_survey_report, survey_import
from django.views import static


class ExtraContextTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(ExtraContextTemplateView, self).get_context_data(**kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

admin.autodiscover()

urlpatterns = [
    
    # Core Application
    url(r'^$', status_page, name='status'),
    
    # Vaers
    url(r'^vaers/', include('ESP.vaers.urls')),
    
    # Survey 
    url(r'^survey_import/', survey_import, name='survey_import'),
    url(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    url(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Login and Logout
    url(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    
    # About
    url(r'^about/', ExtraContextTemplateView.as_view(
        template_name='about.html',
        extra_context={'title': 'About ESP'}
    ), name='about'),
    
    
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),
#   (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
    
    # Configuration
    url(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #url(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    url(r'^util/', include('ESP.ui.urls')),
    
    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #url(r'^codes', code_maintenance),
    #url(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #url(r'^/$', include('ESP.ui.urls')),
]

ESP/vaers/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.conf.urls import include

from ESP.vaers import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^casetable$', views.list_cases),
    url(r'^notify/(?P<id>\d+)/$', views.notify),
    url(r'^report$', views.report),

    # Vaccine and Manufacturer Mapping
    url(r'^vaccines/', include('ESP.vaers.vaccine.urls')),
    
    # ptype can be digest or case.  digest takes a digest value for id, case takes a questionnaire id for id.
    url(r'^(?P<ptype>case|digest)/(?P<id>\w*)/$', views.case_details, name='present_case'),

    #line listing report
    url(r'^download/', views.download_vae_listing, name='download_listing'),    
]


ESP/emr/models.py
'''
                              ESP Health Project
                     Electronic Medical Records Warehouse
                                  Data Models

@authors: Jason McVetta <jason.mcvetta@gmail.com>, Raphael Lullis <raphael.lullis@gmail.com>
@organization: Channing Laboratory - http://www.channing.harvard.edu
@contact: http://esphealth.org
@copyright: (c) 2009-2011 Channing Laboratory
@license: LGPL 3.0 - http://www.gnu.org/licenses/lgpl-3.0.txt
'''

import string
import time
import random
import datetime
import sys
import re
import os

from dateutil.relativedelta import relativedelta
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Q, F
from django.contrib.contenttypes.fields import GenericRelation
from ESP.settings import DATA_DIR, MAX_BMI, MAX_WTKG, MAX_HTCM
from ESP.emr.choices import LOAD_STATUS
from ESP.conf.models import HL7Map
from ESP.conf.common import EPOCH
from ESP.conf.models import LabTestMap
from ESP.static.models import FakeLabs, FakeVitals, FakeMeds, FakeDx_Codes
from ESP.static.models import Dx_code
from ESP.static.models import Allergen
from ESP.static.models import Vaccine
from ESP.conf.models import VaccineManufacturerMap, VaccineCodeMap
from ESP.utils import randomizer
from ESP.utils.utils import log

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Models
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class Provenance(models.Model):
    '''
    Answers the question "Where did this data come from?"
    '''
    provenance_id = models.AutoField(primary_key=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=False)
    # source will contain the filename, if data came from a file
    source = models.CharField(max_length=500, blank=False, db_index=True)
    hostname = models.CharField('Host on which data was loaded', max_length=255, blank=False)
    status = models.CharField(max_length=10, choices=LOAD_STATUS, blank=False, db_index=True)
    raw_rec_count = models.IntegerField('Count of records in incoming file', null=True, default=0)
    valid_rec_count = models.IntegerField('Count of valid records loaded to primary table', blank=False, default=0)
    insert_count = models.IntegerField('Count of records inserted to primary table on last load', null=True, default=0)
    update_count = models.IntegerField('Count of records updated in primary table on last load', null=True, default=0)
    post_load_count = models.IntegerField(
        'Count of records in primary table with this provenance_id upon load completion', null=True, default=0)
    error_count = models.IntegerField('Count of record processing errors during load', blank=False, default=0)
    comment = models.TextField(blank=True, null=True)
    data_date = models.DateField(blank=True, null=True)

    class Meta:
        unique_together = ['timestamp', 'source', 'hostname']

    @staticmethod
    def get_latest_data_date(source_search_str):
        """
        Return the latest data date for the Provenance objects whose
        source contains the source_search_str
        """
        qs = Provenance.objects.filter(source__icontains=source_search_str).order_by('-data_date')
        if qs:
            return qs.first().data_date
        else:
            return datetime.date.today()

    @staticmethod
    def fake():
        data_faker = 'Data Faker App'
        try:
            return Provenance.objects.get(source=data_faker)
        except:
            return Provenance.objects.create(
                source=data_faker, status='loaded', hostname='fake',
                comment='Data Faker App add data that should be used ' \
                        'for testing and development purposes only')


    def __str__(self):
        return '%s | %s | %s' % (self.source, self.timestamp, self.hostname)


class EtlError(models.Model):
    '''
    An ETL error, usually corresponding with a single bad line in a data file.
    '''
    timestamp = models.DateTimeField(auto_now_add=True, blank=False)
    provenance = models.ForeignKey(Provenance, blank=False)
    line = models.IntegerField('Line Number', blank=False)
    err_msg = models.CharField(max_length=512, blank=False)
    data = models.TextField()


class LabTestConcordance(models.Model):
    '''
    Concordance table listing all distinct lab test names and codes, and the 
    count results in the database for each test at time table was generated.
    Should be rebuilt after each load of new EMR data.
    '''
    native_code = models.CharField(max_length=100, blank=False, db_index=True)
    native_name = models.CharField(max_length=255, null=True, db_index=True)
    count = models.IntegerField(blank=False)


#===============================================================================
#
#--- ~~~ Medical Records ~~~
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class BaseMedicalRecord(models.Model):
    '''
    Abstract base class for a medical record
    '''
    provenance = models.ForeignKey(Provenance, blank=False)
    # this is the unique identifier for this record in the source EMR system 
    natural_key = models.CharField(unique=True, blank=True, null=True, max_length=128,
                                   help_text='Unique Record identifier in source EMR system')
    created_timestamp = models.DateTimeField(auto_now_add=True, blank=False)
    updated_timestamp = models.DateTimeField(auto_now=True, blank=False, db_index=True)

    class Meta:
        abstract = True

    def get_hl7(self, mod, var, val, typ):
        '''
        Returns hl7 type associated with variable val, or throws an exception
        '''
        if val:
            try:
                mapObj = HL7Map.objects.get(model=mod, variable=var, value=val)
                if typ == 'value':
                    ret = mapObj.hl7.value
                elif typ == 'description':
                    ret = mapObj.hl7.description
                elif typ == 'codesys':
                    ret = mapObj.hl7.codesys
                elif typ == 'version':
                    ret = mapObj.hl7.version
            except ObjectDoesNotExist:
                log.error('No mapped values for model: %s, variable: %s, value: %s' % (mod, var, val))
                sys.exit(1)
        else:
            #if the value being passed is empty, return empty
            ret = ''
        return ret


class Provider(BaseMedicalRecord):
    '''
    A medical care provider
    '''
    last_name = models.CharField('Last Name', max_length=200, blank=True, null=True)
    first_name = models.CharField('First Name', max_length=200, blank=True, null=True)
    middle_name = models.CharField('Middle_Name', max_length=200, blank=True, null=True)
    title = models.CharField('Title', max_length=50, blank=True, null=True)
    dept_natural_key = models.CharField('Primary Department identifier in source EMR system', max_length=100,
                                        blank=True, null=True)
    dept = models.CharField('Primary Department', max_length=200, blank=True, null=True)
    dept_address_1 = models.CharField('Primary Department Address 1', max_length=100, blank=True, null=True)
    dept_address_2 = models.CharField('Primary Department Address 2', max_length=100, blank=True, null=True)
    dept_city = models.CharField('Primary Department City', max_length=20, blank=True, null=True)
    dept_state = models.CharField('Primary Department State', max_length=20, blank=True, null=True)
    dept_zip = models.CharField('Primary Department Zip', max_length=20, blank=True, null=True)
    # Large max_length value for area code because Atrius likes to put descriptive text into that field
    area_code = models.CharField('Primary Department Phone Areacode', max_length=50, blank=True, null=True)
    telephone = models.CharField('Primary Department Phone Number', max_length=50, blank=True, null=True)
    center_id = models.CharField('Center ID', max_length=100, blank=True, null=True, db_index=True)
    dept_country = models.CharField('Primary Dept country', max_length=100, blank=True, null=True)
    dept_county_code = models.CharField('Primary Dept county code', max_length=10, blank=True, null=True)
    tel_country_code = models.CharField('Primary Dept country tel code', max_length=10, blank=True, null=True)
    tel_ext = models.CharField('Primary Dept phone extension', max_length=10, blank=True, null=True)
    call_info = models.CharField('Primary Dept address comment', max_length=200, blank=True, null=True)
    clin_address1 = models.CharField('Clinician Address Line 1', max_length=100, blank=True, null=True)
    clin_address2 = models.CharField('Clinician Address Line 2', max_length=100, blank=True, null=True)
    clin_city = models.CharField('Clinician City', max_length=50, blank=True, null=True)
    clin_state = models.CharField('Clinician State', max_length=50, blank=True, null=True)
    clin_zip = models.CharField('Clinician Zip Code', max_length=10, blank=True, null=True)
    clin_country = models.CharField('Clinician Country', max_length=100, blank=True, null=True)
    clin_county_code = models.CharField('Clinician county code', max_length=10, blank=True, null=True)
    clin_tel_country_code = models.CharField('Clinician country tel code', max_length=10, blank=True, null=True)
    clin_areacode = models.CharField('Clinician Phone area code', max_length=5, blank=True, null=True)
    clin_tel = models.CharField('Clinician Phone number', max_length=10, blank=True, null=True)
    clin_tel_ext = models.CharField('Clinician Extension', max_length=10, blank=True, null=True)
    clin_call_info = models.CharField('Clinician address comment', max_length=200, blank=True, null=True)
    suffix = models.CharField('Name suffix', max_length=20, blank=True, null=True)
    dept_addr_type = models.CharField(max_length=20, blank=True, null=True)

ESP/conf/forms.py
'''
                              ESP Health Project
                             Configuration Module
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms


class CodeMappingForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    native_name = forms.CharField(max_length=255, required=True)
    native_code = forms.CharField(max_length=100, required=True)

ESP/vaers/vaccine/forms.py
from django import forms

from ESP.conf.models import Vaccine, ImmunizationManufacturer

STANDARD_VACCINES = ((x.code, unicode(x)) for x in 
                     Vaccine.acceptable_mapping_values())

STANDARD_MANUFACTURERS = ((x.code, unicode(x)) for x in 
                          ImmunizationManufacturer.objects.all())


class StandardVaccinesForm(forms.Form):
    vaccine = forms.ChoiceField(choices=STANDARD_VACCINES)

class StandardManufacturersForm(forms.Form):
    manufacturer = forms.ChoiceField(choices=STANDARD_MANUFACTURERS)

ESP/templates/ui/case_list.html
{% extends "base.html" %}
{% load templatefilters %}
{% load django_tables2 %}

{% block extrascript %}

    <script type="text/javascript"
            src="{{ site_javascript_folder }}dropdown-check-list.1.1/js/ui.dropdownchecklist-1.1-min.js"></script>
    <link type="text/css" rel="stylesheet" media="screen"
          href="{{ site_javascript_folder }}dropdown-check-list.1.1/css/ui.dropdownchecklist.standalone.css"/>


    <script type="text/javascript">
        $(document).ready(function () {
            $.datepicker.setDefaults({
                changeMonth: true,
                changeYear: true,
            });
            $('#id_date_after').datepicker();
            $('#id_date_before').datepicker();
            $('#id_status').dropdownchecklist({width: 300, emptyText: "Select..."});
            $('#id_condition').dropdownchecklist({width: 300, emptyText: "Select..."});
            $('#id_provider_dept').dropdownchecklist({width: 300, maxDropHeight: 350, emptyText: "Select..."});
        });
    </script>
{% endblock %}

{% block extrastyle %}

    <style type="text/css" media="all">
        form ol {
            list-style: none;
        }

        #search_div {
            float: left;
        }

        #summary_div {
            float: right;
        }

        #form_table {
            border: 0;
        }

        #form_table th {
            text-align: right;
            border: 0;
        }

        #form_table td {
            text-align: left;
            border: 0;
        }
    </style>

{% endblock %}

{% block content %}

    <div id="search_div">
        <h2>Filter</h2>

        <form id="search_form" method="GET" action="{% url 'nodis_cases_all' %}">
            <table id="form_table">
                {{ search_form.as_table }}
            </table>
            <p>
                <input type="submit" value="Update Results"/>
                <a href="{{ clear_search_path }}">Reset Filter</a>

            <p>
                <a href="{{ full_path }}&export_csv=case_list">Export case list to CSV file</a>

            <p>
        </form>
    </div>

    <div style="clear:both;"/>

    <h2>Cases by Patient</h2>

    {% render_table table %}

{% endblock %}

ESP/templates/ui/labtest_detail.html
{% extends "base.html" %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
{% endblock %}

{% block content %}

<p>
    <em>Click test code to download CSV file.</em>
</p>

<table>
    <tr>
        <th>Native Code
        <th>Native Name(s)
        <th>Non-Numeric Results
        <th>Min Numeric Result
        <th>Max Numeric Result
        <th>Reference Low(s)
        <th>Reference High(s)
        <th>Result Count
    </tr>
    {% for test in details %}
    <tr>
        <td><a href="{% url 'labtest_csv' test.native_code %}">{{ test.native_code }}</a>
        <td>{{ test.native_names|join:"<br>" }}
        <td>{{ test.result_strings|join:"<br>" }}
        <td>{{ test.min_result_float }}
        <td>{{ test.max_result_float }}
        <td>{{ test.ref_low_values|join:"<br>" }}
        <td>{{ test.ref_high_values|join:"<br>" }}
        <td>{{ test.count }}
    </tr>
    {% endfor %}
</table>

<p>
    <a href="{% url 'labtest_lookup' %}">Back to Lab Test Lookup form</a>
</p>


{% endblock%}

ESP/templates/ui/labtest_lookup.html
{% extends "base.html" %}

{% block extrastyle %}
    <link rel="stylesheet" type="text/css" media="screen" href="{{ site_javascript_folder }}/flexigrid/css/flexigrid/flexigrid.css" />
{% endblock %}

{% block content %}

<p>
<form id="lookup_form" action="{% url 'labtest_lookup' %}" method="POST">
    <table>
        {{ lookup_form.as_p }}
    </table>
    <input type="submit" name="lookup" value="Search Tests" />
    {% csrf_token %}
</form>
</p>



{% if tests %}
<hr>
<h2>Results</h2>
<form id='native_codes' action="{% url 'labtest_detail' %}" method='POST'>
    <input type="submit" name="detail" value="View Detail" />
    <table>
    {{ result_form }}
    </table>
</form>
{% endif %}

{% endblock%}

ESP/templates/ui/map_native_code.html
{% extends 'base.html' %}

{% block extrastyle %}
    <style type="text/css">
    table {
        border-width: thin;
        border-spacing: 0;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: white;
    }
    table th {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    table td {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    </style>
{% endblock %}


{% block content %}

<div style="float:right;">

    <h2>Result Strings</h2>
    <blockquote>
        <p>10 most popular:
        <table>
            <tr>
                <th>Result
                <th>Lab Record Count
            </tr>
            {% for item in result_strings %}
            <tr>
                <td>{{ item.result_string }}
                <td>{{ item.count }}
            </tr>
            {% endfor %}
        </table>
    </blockquote>

    <h2>Reference High Values</h2>
    <p>
        Number of results <em>with</em> numeric result, but <em>without</em> 
        reference high: 
        <br>
        {{ without_ref_high }} ({{ without_ref_high_percent|floatformat:3 }}%).
    </p>
    <blockquote>
        <p>10 most popular:
        <table>
            <tr>
                <th>Reference High Value
                <th>Lab Record Count
            </tr>
            {% for item in ref_high_values %}
            <tr>
                <td>{{ item.ref_high_string }}
                <td>{{ item.count }}
            </tr>
            {% endfor %}
        </table>
    </blockquote>

</div>

<h2>Native Code</h2> 
<p>{{ native_code }}</p>

<h2>Native Names</h2> 
<p>{{ native_names|join:"<br>" }}</p>

<h2>Procedure Names</h2>
<p>{{ procedure_names|join:"<br>" }}</p>

<h2>Record Count</h2>
<p>
    {{ count }}
    <br>(Number of records in database with this native code)
</p>

<h2>Select an Abstract Lab</h2>
<form method="POST" action="{% url 'map_native_code' native_code %}">
    {{ form.as_p }}
    <p>
        <input type="submit" value="Map It!">
        &nbsp;
        <a href="{% url 'unmapped_labs_report' %}">cancel</a>
        &nbsp;
        <a href="{% url 'ignore_code' native_code %}">ignore</a>
    </p>
    {% csrf_token %}
</form>

<hr>

<h2>Comment Values</h2>

<p>10 most popular:
<table>
    <tr>
        <th>Comment Value
        <th>Lab Record Count
    </tr>
    {% for item in comments %}
    <tr>
        <td>{{ item.comment }}
        <td>{{ item.count }}
    </tr>
    {% endfor %}
</table>

{% endblock %}

ESP/templates/ui/survey_report.html
{% extends 'base.html' %}


{% block content %}
<p>Date:  {{ today_string }}
<br>Site:  {{ site_name }}


<h2>
    <hr>
    {{ subtitle }}
    <hr>
</h2>

<p>
    <a href="{{ full_path }}&export_csv=brfssdemo_report">Export Survey Report to CSV file</a>
 <p>

{% for table in tables %}
<div id="new_case_summary" style="float: left;">
    <h3>
         {{ table.0 }}
    </h3>
    
    <table id="new_case_summary_table1">
    
    <tr>
     {% for item in table.1 %}
           <th> {{ item.name }}   </th>
            
         {% endfor %}
        {% for row in table.2 %}
         <tr> 
         
        {% for col in row %}
            {% if col %}
                <td> {{ col }} </td>
            {% else %}
                <td> </td>
            {% endif %}
         {% endfor %}
            
        </tr>
        {% endfor %}
    </table>
    
</div>

  {% endfor %}
 
 
<p style="clear: left;">&nbsp;</p>


<div style="clear: both;" />


{% comment %}

{% endcomment %}

{% endblock %}

ESP/templates/ui/unmapped_labs.html
{% extends 'base.html' %}


{% block extrastyle %}
    <style type="text/css">
    table {
        border-width: thin;
        border-spacing: 0;
        border-style: solid;
        border-color: gray;
        border-collapse: separate;
        background-color: white;
    }
    table th {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    table td {
        border-width: thin;
        padding: 0.5em;
        border-style: solid;
        border-color: gray;
        background-color: white;
        -moz-border-radius: ;
    }
    </style>
{% endblock %}

{% block content %}

<p>
    Searching lab native names for these strings:
    <table>
    <tr> <td>
        {% for s in search_strings %}
          {{ s }} <BR>
	        {% if forloop.counter|divisibleby:"10" %} 
	        </td>
	          {% if not forloop.last %}
	            <td>
	            {% endif %}
	        {% endif %}
        {% endfor %}
    </tr> 
    </table>
</p>


<form method="POST" action="{% url 'ignore_code_set' %}" >
	<p>
	<table>
	    <tr>
		<th />
		<th>Native Name</th>
		<th>Native Code</th>
        <th>Procedure Name</th>
		<th>Lab Record Count</th>
		{% if user.is_staff %}
		<th></th>
		{% endif %}
	    </tr>
	    {% for item in unmapped %}
	    <tr>
		<td><input type="checkbox" name="codes" value="{{ item.native_code }}" id="id_codes_{{ forloop.counter }}">
		<td>{{ item.native_name }}</td>
		<td>{{ item.native_code }}</td>
        <td>{{ item.procedure_name }}</td>
		<td>{{ item.count }}</td>
		{% if user.is_staff %}
		<td><a href="{% url 'map_native_code' item.native_code %}">map</a></td>
		{% endif %}
	    </tr>
	    {% endfor %}
	</table>
	</p>
	<p>
		<input type="submit" name="submit" value="Ignore Selected Codes" />
	</p>
</form>


{% endblock %}