ESP/conf/urls.py
'''
                              ESP Health Project
                             Configuration Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django.conf.urls import url
from ESP.conf import views

urlpatterns = [
    url(r'^codes/ignore/(?P<native_code>.+)/$', views.ignore_code, name='ignore_code'),
    #change name worst case .. good point TODO 
    url(r'^codes/reportables/', views.heuristic_reportables, name='heuristic_reportables'),
    url(r'^codes/report', views.heuristic_mapping_report, name='heuristic_mapping_report'),
    #url(r'^json_code_grid', json_code_grid, name='json_code_grid'),
]

ESP/ui/urls.py
'''
                              ESP Health Project
User Interface Module
                               URL Configuration

@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2010 Channing Laboratory
@license: LGPL
'''


from django.conf.urls import url
from ESP.ui import views

urlpatterns = [
    url(r'^labtest/lookup/$', views.labtest_lookup, name='labtest_lookup'),
    url(r'^labtest/detail/$', views.labtest_detail, name='labtest_detail'),
    url(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    url(r'^labtest/linelist/(?P<native_code>.*)$', views.labtest_csv, name='labtest_csv'),
    url(r'^labtest/ignore_set/$', views.ignore_code_set, name='ignore_code_set'),
    url(r'^labtest/map/(?P<native_code>.+)/$', views.map_native_code, name='map_native_code'),
    url(r'^labtest/unmapped/$', views.unmapped_labs_report, name='unmapped_labs_report'),
    #
    #-------------------------------------------------------------------------------
    # Nodis
    #-------------------------------------------------------------------------------
    #
    url(r'^cases/$', views.case_list, {'status': 'all'}, name='nodis_cases_all'),
    url(r'^cases/list/awaiting_review/$', views.case_list, {'status': 'await'}, name='nodis_cases_awaiting_review'),
    url(r'^cases/list/under_review/$', views.case_list, {'status': 'under'}, name='nodis_cases_under_review'),
    url(r'^cases/list/queued/$', views.case_list, {'status': 'queued'}, name='nodis_cases_queued'),
    url(r'^cases/list/sent/$', views.case_list, {'status': 'sent'}, name='nodis_cases_sent'),
    url(r'^cases/list/requeued/$', views.case_list, {'status': 'requeued'}, name='nodis_cases_requeued'),
    #
    # Case Detail
    #
    url(r'^cases/view/(?P<case_id>\d+)/$', views.case_detail, name='nodis_case_detail'),
    url(r'^cases/viewpert/(?P<case_id>\d+)/$', views.pertussis_detail, name='nodis_pertussis_detail'),
    url(r'^cases/update/(?P<case_id>\d+)/$', views.case_status_update, name='nodis_case_update'),
    url(r'^cases/transmit/(?P<case_id>\d+)/$', views.case_queue_for_transmit, name='nodis_case_transmit'),
    url(r'^provider/(?P<provider_id>\w+)/$', views.provider_detail, name='provider_detail'),
    url(r'^patient/(?P<patient_pk>\d+)/records/$', views.all_records, name='all_records'),
    #
    # Validator
    #
    url(r'^validate/$', views.validator_summary, name='validator_summary'),
    url(r'^validate/missing/$', views.validate_missing, name='validate_missing'),
    url(r'^validate/missing/case/(?P<result_id>\d+)/$', views.missing_case_detail, name='missing_case_detail'),
    url(r'^validate/new/$', views.validate_new, name='validate_new'),
    url(r'^validate/similar/$', views.validate_similar, name='validate_similar'),
    url(r'^validate/exact/$', views.validate_exact, name='validate_exact'),

]

ESP/urls.py
'''
URLs for entire ESP Health django project

'''
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.views import login
from django.contrib.auth.views import logout
from ESP.settings import MEDIA_ROOT
from ESP.ui.views import status_page
from ESP.ui.views_survey import generate_survey_report, view_survey_report, survey_import
from django.views import static


class ExtraContextTemplateView(TemplateView):
    extra_context = None

    def get_context_data(self, **kwargs):
        context = super(ExtraContextTemplateView, self).get_context_data(**kwargs)
        if self.extra_context:
            context.update(self.extra_context)
        return context

admin.autodiscover()

urlpatterns = [
    
    # Core Application
    url(r'^$', status_page, name='status'),
    
    # Vaers
    url(r'^vaers/', include('ESP.vaers.urls')),
    
    # Survey 
    url(r'^survey_import/', survey_import, name='survey_import'),
    url(r'^view_survey_report/', view_survey_report, name='view_survey_report'),
    url(r'^generate_survey_report/', generate_survey_report, name='generate_survey_report'),

    # Login and Logout
    url(r'^login/?$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/?$', logout, {'next_page': '/'}, name='logout'),
    
    # About
    url(r'^about/', ExtraContextTemplateView.as_view(
        template_name='about.html',
        extra_context={'title': 'About ESP'}
    ), name='about'),
    
    
    # Django Admin
    url(r'^admin/', include(admin.site.urls)),
#   (r'^admin/doc/', include('django.contrib.admindocs.urls'),

    url(r'^media/(?P<path>.*)$', static.serve, {'document_root': MEDIA_ROOT}),
    
    # Configuration
    url(r'^conf/', include('ESP.conf.urls')),
    
    # Nodis
    #url(r'^nodis/', include('ESP.nodis.urls')),
    
    # Nodis
    url(r'^util/', include('ESP.ui.urls')),
    
    #
    #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    #
    #url(r'^codes', code_maintenance),
    #url(r'^json_code_grid', json_code_grid, name='json_code_grid'),
    #url(r'^/$', include('ESP.ui.urls')),
]

ESP/vaers/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.conf.urls import include

from ESP.vaers import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^casetable$', views.list_cases),
    url(r'^notify/(?P<id>\d+)/$', views.notify),
    url(r'^report$', views.report),

    # Vaccine and Manufacturer Mapping
    url(r'^vaccines/', include('ESP.vaers.vaccine.urls')),
    
    # ptype can be digest or case.  digest takes a digest value for id, case takes a questionnaire id for id.
    url(r'^(?P<ptype>case|digest)/(?P<id>\w*)/$', views.case_details, name='present_case'),

    #line listing report
    url(r'^download/', views.download_vae_listing, name='download_listing'),    
]


ESP/emr/models.py
'''
                              ESP Health Project
                     Electronic Medical Records Warehouse
                                  Data Models

@authors: Jason McVetta <jason.mcvetta@gmail.com>, Raphael Lullis <raphael.lullis@gmail.com>
@organization: Channing Laboratory - http://www.channing.harvard.edu
@contact: http://esphealth.org
@copyright: (c) 2009-2011 Channing Laboratory
@license: LGPL 3.0 - http://www.gnu.org/licenses/lgpl-3.0.txt
'''

import string
import time
import random
import datetime
import sys
import re
import os

from dateutil.relativedelta import relativedelta
from django.core.exceptions import ObjectDoesNotExist
from django.db import models
from django.db.models import Q, F
from django.contrib.contenttypes.fields import GenericRelation
from ESP.settings import DATA_DIR, MAX_BMI, MAX_WTKG, MAX_HTCM
from ESP.emr.choices import LOAD_STATUS
from ESP.conf.models import HL7Map
from ESP.conf.common import EPOCH
from ESP.conf.models import LabTestMap
from ESP.static.models import FakeLabs, FakeVitals, FakeMeds, FakeDx_Codes
from ESP.static.models import Dx_code
from ESP.static.models import Allergen
from ESP.static.models import Vaccine
from ESP.conf.models import VaccineManufacturerMap, VaccineCodeMap
from ESP.utils import randomizer
from ESP.utils.utils import log

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#
# Models
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class Provenance(models.Model):
    '''
    Answers the question "Where did this data come from?"
    '''
    provenance_id = models.AutoField(primary_key=True)
    timestamp = models.DateTimeField(auto_now_add=True, blank=False)
    # source will contain the filename, if data came from a file
    source = models.CharField(max_length=500, blank=False, db_index=True)
    hostname = models.CharField('Host on which data was loaded', max_length=255, blank=False)
    status = models.CharField(max_length=10, choices=LOAD_STATUS, blank=False, db_index=True)
    raw_rec_count = models.IntegerField('Count of records in incoming file', null=True, default=0)
    valid_rec_count = models.IntegerField('Count of valid records loaded to primary table', blank=False, default=0)
    insert_count = models.IntegerField('Count of records inserted to primary table on last load', null=True, default=0)
    update_count = models.IntegerField('Count of records updated in primary table on last load', null=True, default=0)
    post_load_count = models.IntegerField(
        'Count of records in primary table with this provenance_id upon load completion', null=True, default=0)
    error_count = models.IntegerField('Count of record processing errors during load', blank=False, default=0)
    comment = models.TextField(blank=True, null=True)
    data_date = models.DateField(blank=True, null=True)

    class Meta:
        unique_together = ['timestamp', 'source', 'hostname']

    @staticmethod
    def get_latest_data_date(source_search_str):
        """
        Return the latest data date for the Provenance objects whose
        source contains the source_search_str
        """
        qs = Provenance.objects.filter(source__icontains=source_search_str).order_by('-data_date')
        if qs:
            return qs.first().data_date
        else:
            return datetime.date.today()

    @staticmethod
    def fake():
        data_faker = 'Data Faker App'
        try:
            return Provenance.objects.get(source=data_faker)
        except:
            return Provenance.objects.create(
                source=data_faker, status='loaded', hostname='fake',
                comment='Data Faker App add data that should be used ' \
                        'for testing and development purposes only')


    def __str__(self):
        return '%s | %s | %s' % (self.source, self.timestamp, self.hostname)


class EtlError(models.Model):
    '''
    An ETL error, usually corresponding with a single bad line in a data file.
    '''
    timestamp = models.DateTimeField(auto_now_add=True, blank=False)
    provenance = models.ForeignKey(Provenance, blank=False)
    line = models.IntegerField('Line Number', blank=False)
    err_msg = models.CharField(max_length=512, blank=False)
    data = models.TextField()


class LabTestConcordance(models.Model):
    '''
    Concordance table listing all distinct lab test names and codes, and the 
    count results in the database for each test at time table was generated.
    Should be rebuilt after each load of new EMR data.
    '''
    native_code = models.CharField(max_length=100, blank=False, db_index=True)
    native_name = models.CharField(max_length=255, null=True, db_index=True)
    count = models.IntegerField(blank=False)


#===============================================================================
#
#--- ~~~ Medical Records ~~~
#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


class BaseMedicalRecord(models.Model):
    '''
    Abstract base class for a medical record
    '''
    provenance = models.ForeignKey(Provenance, blank=False)
    # this is the unique identifier for this record in the source EMR system 
    natural_key = models.CharField(unique=True, blank=True, null=True, max_length=128,
                                   help_text='Unique Record identifier in source EMR system')
    created_timestamp = models.DateTimeField(auto_now_add=True, blank=False)
    updated_timestamp = models.DateTimeField(auto_now=True, blank=False, db_index=True)

    class Meta:
        abstract = True

    def get_hl7(self, mod, var, val, typ):
        '''
        Returns hl7 type associated with variable val, or throws an exception
        '''
        if val:
            try:
                mapObj = HL7Map.objects.get(model=mod, variable=var, value=val)
                if typ == 'value':
                    ret = mapObj.hl7.value
                elif typ == 'description':
                    ret = mapObj.hl7.description
                elif typ == 'codesys':
                    ret = mapObj.hl7.codesys
                elif typ == 'version':
                    ret = mapObj.hl7.version
            except ObjectDoesNotExist:
                log.error('No mapped values for model: %s, variable: %s, value: %s' % (mod, var, val))
                sys.exit(1)
        else:
            #if the value being passed is empty, return empty
            ret = ''
        return ret


class Provider(BaseMedicalRecord):
    '''
    A medical care provider
    '''
    last_name = models.CharField('Last Name', max_length=200, blank=True, null=True)
    first_name = models.CharField('First Name', max_length=200, blank=True, null=True)
    middle_name = models.CharField('Middle_Name', max_length=200, blank=True, null=True)
    title = models.CharField('Title', max_length=50, blank=True, null=True)
    dept_natural_key = models.CharField('Primary Department identifier in source EMR system', max_length=100,
                                        blank=True, null=True)
    dept = models.CharField('Primary Department', max_length=200, blank=True, null=True)
    dept_address_1 = models.CharField('Primary Department Address 1', max_length=100, blank=True, null=True)
    dept_address_2 = models.CharField('Primary Department Address 2', max_length=100, blank=True, null=True)
    dept_city = models.CharField('Primary Department City', max_length=20, blank=True, null=True)
    dept_state = models.CharField('Primary Department State', max_length=20, blank=True, null=True)
    dept_zip = models.CharField('Primary Department Zip', max_length=20, blank=True, null=True)
    # Large max_length value for area code because Atrius likes to put descriptive text into that field
    area_code = models.CharField('Primary Department Phone Areacode', max_length=50, blank=True, null=True)
    telephone = models.CharField('Primary Department Phone Number', max_length=50, blank=True, null=True)
    center_id = models.CharField('Center ID', max_length=100, blank=True, null=True, db_index=True)
    dept_country = models.CharField('Primary Dept country', max_length=100, blank=True, null=True)
    dept_county_code = models.CharField('Primary Dept county code', max_length=10, blank=True, null=True)
    tel_country_code = models.CharField('Primary Dept country tel code', max_length=10, blank=True, null=True)
    tel_ext = models.CharField('Primary Dept phone extension', max_length=10, blank=True, null=True)
    call_info = models.CharField('Primary Dept address comment', max_length=200, blank=True, null=True)
    clin_address1 = models.CharField('Clinician Address Line 1', max_length=100, blank=True, null=True)
    clin_address2 = models.CharField('Clinician Address Line 2', max_length=100, blank=True, null=True)
    clin_city = models.CharField('Clinician City', max_length=50, blank=True, null=True)
    clin_state = models.CharField('Clinician State', max_length=50, blank=True, null=True)
    clin_zip = models.CharField('Clinician Zip Code', max_length=10, blank=True, null=True)
    clin_country = models.CharField('Clinician Country', max_length=100, blank=True, null=True)
    clin_county_code = models.CharField('Clinician county code', max_length=10, blank=True, null=True)
    clin_tel_country_code = models.CharField('Clinician country tel code', max_length=10, blank=True, null=True)
    clin_areacode = models.CharField('Clinician Phone area code', max_length=5, blank=True, null=True)
    clin_tel = models.CharField('Clinician Phone number', max_length=10, blank=True, null=True)
    clin_tel_ext = models.CharField('Clinician Extension', max_length=10, blank=True, null=True)
    clin_call_info = models.CharField('Clinician address comment', max_length=200, blank=True, null=True)
    suffix = models.CharField('Name suffix', max_length=20, blank=True, null=True)
    dept_addr_type = models.CharField(max_length=20, blank=True, null=True)

ESP/conf/forms.py
'''
                              ESP Health Project
                             Configuration Module
                              User Interface Forms


@authors: Jason McVetta <jason.mcvetta@gmail.com>
@organization: Channing Laboratory http://www.channing.harvard.edu
@copyright: (c) 2009 Channing Laboratory
@license: LGPL
'''


from django import forms


class CodeMappingForm(forms.Form):
    '''
    Form for mapping Native Code to LOINC
    '''
    native_name = forms.CharField(max_length=255, required=True)
    native_code = forms.CharField(max_length=100, required=True)

ESP/vaers/vaccine/forms.py
from django import forms

from ESP.conf.models import Vaccine, ImmunizationManufacturer

STANDARD_VACCINES = ((x.code, unicode(x)) for x in 
                     Vaccine.acceptable_mapping_values())

STANDARD_MANUFACTURERS = ((x.code, unicode(x)) for x in 
                          ImmunizationManufacturer.objects.all())


class StandardVaccinesForm(forms.Form):
    vaccine = forms.ChoiceField(choices=STANDARD_VACCINES)

class StandardManufacturersForm(forms.Form):
    manufacturer = forms.ChoiceField(choices=STANDARD_MANUFACTURERS)

ESP/templates/pages/vaers/collect_feedback.html
<div id="inp_case_comment">
  <div>{{ headline }}</div>
  <form id="frm_feedback" method="POST" action="{{ url }}">
    <textarea >{{ instructions }}</textarea>
    <input type="submit" value="Submit" />
   {% csrf_token %}
  </form>
</div>

ESP/templates/pages/vaers/home.html
{% extends "base.html" %}
{% block extrascript %}
<script type="text/javascript" src="{{ site_javascript_folder }}vaers.js">
</script>

<script type="text/javascript">
$(document).ready(function() {
   makeGrid($("#case_table"), "{% url 'vaers.views.list_cases' %}");
});
</script>
{% endblock %}

{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{{ site_css_folder }}vaers.css" />
<link rel="stylesheet" type="text/css" href="{{ site_javascript_folder }}flexigrid/css/flexigrid/flexigrid.css" />

{% endblock %}



{% block content %}
<div class="warning" id="banner_no_email">
  <h2>No email to send notifications</h2>
  <p>
    You haven't set the email address where the notifications will be
    sent out to. Please, <span class="button" onClick="promptEmail();">click here</span> to
    be able to receive demonstration messages.
  </p>
</div>

<div style="display:none;" class="info" id="banner_info_email">
  Currently set to send detailed reports to <span id="email_address"></span>. <span class="button" onClick="promptEmail();">Change it here</span>.
</div>

<div class="warning" id="banner">
  <span id="btn_close_banner" onClick="hideDemoWarning();" class="button">Dismiss</span>
  <div id="banner_content">
  <h2>Warning: Feature is only for demonstration purposes.</h2>  
  <p>
    In a "real world" scenario, cases that are detected by ESP are
    mailed to the physician with a randomly generated URL. To receive
    such link, just click "Get Details" button for one of the
    cases. You need to provide your email address, and
    you <em>should</em> receive an email with the link to the detailed
    case information.
  </p>
  </div>

</div>

{% include "widgets/vaers/case_grid.html" %} 


{% endblock %}

ESP/templates/pages/vaers/identify.html
{% extends "vaers.html" %}
{% block content %}
<div>
    Please confirm that you are {{ case.patient.pcp.full_name }} 
    and that you are the care provider for {{ case.patient.full_name }}
    <div>
      <form action="{% url 'verify_case' case.digest %}" method="POST">
	<input type="hidden" value="{{ case.patient.pcp.id }}"/>
	<input type="radio" name="provider_confirmation" value="confirmed">Yes</input>
	<input type="radio" name="provider_confirmation" value="">No</input>
	<input type="submit" value="Submit" />
        {% csrf_token %}
      </form>
    </div>
</div>
{% endblock %}

ESP/templates/pages/vaers/manufacturers.html
{% extends "vaers.html" %}


{% block content %}
<div>
  <h1>Vaccine Manufacturer</h1>
  <div style="float:left;">
    <h2>Unmapped</h2>
    <table>
      {% for manufacturer in unmapped_manufacturers %}
      <tr>
	<td>{{manufacturer.name}}</td>
	<td><a href="{% url 'vaers.vaccine.views.manufacturer_detail' manufacturer.id %}">Edit</a></td>
      </tr>
      {% endfor %}    
    </table>
  </div>
  <div style="float:right;">
    <h2>Mapped</h2>
    <table>
      {% for manufacturer in mapped_manufacturers %}
      <tr>
	<td>{{manufacturer.name}}</td>
	<td>{{manufacturer.canonical_code}}</td>
      </tr>
      {% endfor %}
    </table>
  </div>

</div>

{% endblock %}

ESP/templates/pages/vaers/notify.html
{% extends "vaers.html" %}


{% block content %}
Notify
{% endblock %}

ESP/templates/pages/vaers/present.html
{% extends "vaers.html" %}
{% block extrastyle %}
<link rel="stylesheet" type="text/css" href="{{ site_css_folder }}vaers.css" />
{% endblock %}
{% block extrascript %}

<script type="text/javascript" src="{{ site_javascript_folder }}vaers.js">

</script>

{% endblock%}

{% block content %}
<table border="0"> 
<tr >
<td style="border:0">
<table id="tbl_case_details" 
  <tr>
  <th align = left >Patient name <bR> [MRN] </th>
    <td>{{ case.patient.full_name  }} <BR> [{{ case.patient.mrn  }}]</td>
  
    <th align = left>Gender</th>
    <td> {% ifequal  case.patient.gender 'F' %} 
          Female 
          {% else %}
          Male 
          {% endifequal %}
     </td>
  </tr>
  <tr>
    <th align = left>Date of birth [age]</th>
    <td>{{ case.patient.date_of_birth|date:"d-M-Y" }} 
    {% if  case.patient.age.years  > 2 %}
      [{{ case.patient.age.years }} years]
    {% else %}
     [{{ case.patient.age.months }} months]
    {% endif %}
    
    </td>
      
    <th align = left>Telephone number</th>
    <td>({{ case.patient.areacode }}) {{ case.patient.tel }}</td>
  </tr> 
</table>
</td>
<td style="border:0">
<table id="tbl_case_details" >

  <tr>
  <th align = left>Reviewing Clinician</th>
    <td>{{ questionnaire.provider.full_name  }}</td>
  </tr> 
  <tr>
  <th align = left>Primary Care Provider</th>
    <td> {{ case.patient.pcp }}</td>
  </tr> 
  
</table>

</td>
</tr>
</table>
<BR>

<b>Your patient received the following vaccination on {{ case.date|date:"M d, Y"}} 
   <br></b>
  {% for vacc in case.immunizations.all %}
	  {{ vacc.name }}  <BR>
  {% endfor %}
<br>
  <b>We noted the following potentially concerning events after vaccination: </b>
  <BR><BR>
 <table border="0"> 
<tr >
<td style="border:0">
<table border="0" id="tbl_case_details">
<tr>
  <th align = left>Event Date</th>
  <th align = left>Days Since Vaccine(s) given</th>
  <th align = left>Encounter Type</th>
  <th align = left>Labs</th>
  <th align = left>Diagnosis</th>
  <th align = left>Prescription</th>
  <th align = left>Allergies</th>
</tr>
<!-- add comments here 
-->

{% for event in case.highest_event_category %}
 <tr>
  
  {% ifequal content_type_enc event.content_type %}
    
    <td>  {{ event.content_object.date|date:"d-M-Y"}} </td>
    <td> {{ event.gap }} </td>
    <td> {% ifequal event.content_object.encounter_type 'VISIT' %}
            Ambulatory
          {% endifequal %}   
          {% ifequal event.content_object.encounter_type 'HOSPITALIZATION' %}
            Hospitalized
          {% endifequal %} 
          {% ifequal event.content_object.encounter_type 'ER' %}
            ED
          {% endifequal %}  
    <td></td>
    <td> {{ event.matching_rule_explain }}    </td>
    </td>
    <td></td>
    <td></td>
  {% endifequal %}
  
   {% ifequal content_type_lx event.content_type %}
   
  <td> {{event.content_object.collection_date|date:"d-M-Y"}}</td>
  <td> {{ event.gap }} </td>
  <td></td>
  <td> {{ event.content_object.native_name }} {{ event.content_object.result_float|default:"N/A"}} {{ event.content_object.ref_unit}}
     {% if  event.last_known_value  %}
     <BR>(last value prior to vaccination {{ event.last_known_value }} on {{ event.last_known_date|date:"d-M-Y" }}) 
     {% endif %}
     </td>
  <td></td>
  <td></td>
  <td></td>
  
  {% endifequal %}
  
   {% ifequal content_type_rx event.content_type %}
  <td>{{ event.content_object.date|date:"d-M-Y" }} </td>
  <td> {{ event.gap }} </td>
  <td></td><td></td>
  <td></td>
  <td> {{ event.content_object.matching_rule_explain }}  </td>
  <td></td>
  
  {% endifequal %}
  
   {% ifequal content_type_all event.content_type %}
   <td> {{ event.content_object.date_noted|date:"d-M-Y" }}</td>
   <td> {{ event.gap }} </td>
   <td></td><td></td>
   <td></td>
   <td></td>
     <td> {{ event.content_object.name }}  </td>
  
  {% endifequal %}
    
   </tr>
  
  {% endfor %}

</table></td></tr></table>
<BR>
{% if  case.prior_immunizations.all %}
  <b>Note: the patient has also recently received the following vaccine(s):</b><BR>
  {% for vacc in case.prior_immunizations.all %}
	 {{ vacc.date|date:"M d, Y"}} {{ vacc.name }} <BR>
  {% endfor %}
  
  {% endif %}
<form id="frm_case_confirmation" method="POST" action="{% url 'present_case' ptype formid  %}">
 <B>
    <div class="css_state">
    <header>
    <h2>
    <label for="id_state_0">Possible Adverse Event?</label>
    </h2>
  </header>
        {{ form.state }}   
    
    <div id=first style="display:block">
    <label for="id_comment">Comments:</label>
    </div>    
    <div id=second  style="display:none;">
    <label for="id_comment">Please provide details on the likelihood and severity of this possible event:</label>
    </div>    
    <div id=third style="display:none;">
    <label for="id_comment">Please provide details so that we can refine our adverse event detection algorithms:</label>
    </div>    
    <div id=commentbox >
      {{ form.comment }}
     </div>
    <div class="css_ishelpful">
    <header>
    <h2>Please help us assess this automated adverse event reporting tool.</h2>
  </header>
    <label for="id_message_ishelpful">Was this message helpful?</label>
        {{ form.message_ishelpful }}
        
    </div>
    <div class="css_inter_satis">
    <label for="id_interrupts_work">Did it interrupt your work flow?</label>
       {{ form.interrupts_work }}
    <label for="id_satisfaction_num_msg">Has the number of messages recently been:</label> 
     {{ form.satisfaction_num_msg }}    
     </div>
   
 </B>
 
  <input type="submit" value="submit" />
  {% csrf_token %}
</form>
{% endblock %}